name: "Run Container Scan on Super Mario Docker Image with Quality Gate"

# on:
#   push:
#     branches:
#       - main

jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Updated to the latest version

      - name: Read Version Number
        id: version_step
        run: |
          version=$(cat version.txt)
          new_version=$((version + 1))
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Check Docker Image Existence with Retry
        id: image_check
        run: |
          for i in {1..5}; do
            if docker manifest inspect docker.io/gvindio/supermariogitopsproject:${{ env.new_version }} > /dev/null; then
              echo "exists=true" >> $GITHUB_ENV
              break
            else
              echo "Attempt $i: Docker image does not exist for version ${{ env.new_version }}. Retrying in 30 seconds..."
              sleep 30
            fi
            if [ $i -eq 5 ]; then
              echo "Docker image does not exist for version ${{ env.new_version }} after 5 attempts."
              exit 1
            fi
          done

      - name: Get Docker Image from Docker Hub
        if: env.exists == 'true'
        run: |
          docker pull docker.io/gvindio/supermariogitopsproject:${{ env.new_version }}
          docker save -o supermariolatestdockerimage.tar docker.io/gvindio/supermariogitopsproject:${{ env.new_version }}

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/supermariolatestdockerimage.tar
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
