name: "Build and push Super Mario Docker image with dynamic tag to Docker Hub"
 
# on:
#   push:
#     branches:
#       - main

jobs:
  build_push_supermario_docker_image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read and Increment Version
        id: version_step
        run: |
          version=$(cat version.txt)
          new_version=$((version + 1))
          echo "new_version=$new_version" > version.txt
          echo "::set-output name=new_version::$new_version"

      - name: Update Version in Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Increment version to ${{ steps.version_step.outputs.new_version }}"
          git push

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t docker.io/gvindio/supermariogitopsproject:${{ steps.version_step.outputs.new_version }} .
          docker push docker.io/gvindio/supermariogitopsproject:${{ steps.version_step.outputs.new_version }}
